- type: constructionGraph
  id: foldsmugglerpackage
  start: start
  graph:
  - node: start
    edges:
    - to: emptypacket
      steps:
      - material: Cardboard
        amount: 1
        doAfter: 3
  - node: emptypacket
    entity: emptyPacket
